# Generated by Django 5.0.2 on 2024-03-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='career',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
